name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/.ssh && echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
      - run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"
      - run: make
      - run: git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: make deploy
        if: ${{ github.ref == 'refs/heads/main' }}
